spring:
  application:
    name: clsc

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/interns_db?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Spring Security credentials (optional; uncomment to use environment variables)
#  security:
#    user:
#      name: ${SPRING_SECURITY_USERNAME}
#      password: ${SPRING_SECURITY_PASSWORD}

server:
  port: 8081
